AWSTemplateFormatVersion: 2010-09-09 
Parameters:
  InstanceTypeParameter: 
    Type: String 
    Default: t2.small
    Description: Enter instance size. 
  WorkstationIp:
    Type: String
    Description: The IP address of the workstation that can SSH into the instance. 
  AMI:
    Type: String
    Default: ami-052c9ea013e6e3567                        
    Description: Amazon Linux 2023 AMI
  Key:
    Type: String
    Description: The key used to access the instance. 
    Default: ec2-key                                     
Resources: 
  VPC:                                                   
    Type: AWS::EC2::VPC 
    Properties:
      CidrBlock: 216.0.0.0/16                             
      EnableDnsSupport: true 
      EnableDnsHostnames: true 
      InstanceTenancy: default 
      Tags:
        - Key: Name 
          Value: ProjectVPC
  InternetGateway:                                         
    Type: AWS::EC2::InternetGateway 
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment 
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  Subnet1:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2a
      VpcId: !Ref VPC
      CidrBlock: 216.0.10.0/24 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name 
          Value: Pub01Subnet
  Subnet2:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2a                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.20.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: Web01Subnet
  Subnet3:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2a                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.30.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: Was01Subnet
  Subnet4:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2a                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.40.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: DB01Subnet
  Subnet5:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2b                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.110.0/24 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name 
          Value: Pub02Subnet
  Subnet6:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2b                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.120.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: Web02Subnet
  Subnet7:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2b                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.130.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: Was02Subnet
  Subnet8:
    Type: AWS::EC2::Subnet 
    Properties:
      AvailabilityZone: us-west-2b                     
      VpcId: !Ref VPC
      CidrBlock: 216.0.140.0/24 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name 
          Value: DB02Subnet
  RouteTableA:
    Type: AWS::EC2::RouteTable 
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name 
          Value: Public-RT
  RouteTableB:
    Type: AWS::EC2::RouteTable 
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name 
          Value: Private-RT
  InternetRoute:
    Type: AWS::EC2::Route 
    DependsOn: InternetGateway 
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTableA
  NATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref Subnet5
      Tags:
      - Key: Name
        Value: Project-NGW
  RouteNATGateway:
    DependsOn: NATGateway
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableB
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref NATGateway
  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableA
      SubnetId: !Ref Subnet1
  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableA
      SubnetId: !Ref Subnet5
  SubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableB
      SubnetId: !Ref Subnet3
  SubnetRouteTableAssociation4:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableB
      SubnetId: !Ref Subnet4
  SubnetRouteTableAssociation5:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableB
      SubnetId: !Ref Subnet2
  SubnetRouteTableAssociation6:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      RouteTableId: !Ref RouteTableB
      SubnetId: !Ref Subnet6
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupName: "Internet Group"
      GroupDescription: "SSH and web traffic in, all traffic out." 
      VpcId: !Ref VPC
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22' 
          ToPort: '22' 
          CidrIp:  14.52.0.0/16                       
      SecurityGroupEgress: 
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0 
  ElasticIP:
    Type: AWS::EC2::EIP 
    Properties:
      Domain: VPC

